name: 'git-flow-merge-action'
description: 'merge branch to master and develop branch, and add tag'
author: 'Yasuharu Yanamura'
inputs:
  github_token:
    description: 'GitHub token'
  branch:
    description: 'release or hotfix branch'
  tag:
    description: 'tag name'
runs:
  using: 'node12'
  main: 'dist/index.js'
